[package]
name = "rustpcg"
version = "0.1.0"
authors = ["Kyle Harris <kaharrs2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
noise = "0.9"
termion = "3.0"
image = "0.25"
